const dummyData = [{
    name: 'Dr. Rajesh Kumar',
    age: '40',
    location: 'Pune',
    category: 'Physicians',
    education: 'Government Medical College Pune',
    phoneNumber: '1234567890',
    experience: '15',
},
{
    name: 'Dr. Priya Sharma',
    age: '35',
    location: 'Pune',
    category: 'Surgeons',
    education: 'Government Dental College Mumbai',
    phoneNumber: '9876543210',
    experience: '10',
},
{
    name: 'Dr. Aryan Patel',
    age: '45',
    location: 'Pune',
    category: 'Dentists',
    education: 'Government Medical College Hyderabad',
    phoneNumber: '8765432109',
    experience: '20',
},
{
    name: 'Dr. Nandini Gupta',
    age: '38',
    location: 'Pune',
    category: 'Pediatricians',
    education: 'All India Institute of Medical Sciences (AIIMS) Delhi',
    phoneNumber: '7654321098',
    experience: '12',
},
{
    name: 'Dr. Anand Verma',
    age: '42',
    location: 'Pune',
    category: 'Cardiologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '6543210987',
    experience: '18',
},
{
    name: 'Dr. Priyanka Reddy',
    age: '37',
    location: 'Pune',
    category: 'Orthopedic Surgeons',
    education: 'AIIMS Bangalore',
    phoneNumber: '8765432109',
    experience: '15',
},
{
    name: 'Dr. Mohan Singh',
    age: '44',
    location: 'Pune',
    category: 'Gynecologists',
    education: 'Government Medical College Rajasthan',
    phoneNumber: '7654321098',
    experience: '17',
},
{
    name: 'Dr. Sanya Kapoor',
    age: '39',
    location: 'Pune',
    category: 'Ophthalmologists',
    education: 'Government Medical College Kashmir',
    phoneNumber: '9876543210',
    experience: '14',
},
{
    name: 'Dr. Sameer Joshi',
    age: '41',
    location: 'Pune',
    category: 'Dermatologists',
    education: 'AIIMS Leh',
    phoneNumber: '1234567890',
    experience: '16',
},

{
    name: 'Dr. Rajesh Kumar',
    age: '40',
    location: 'Pune',
    category: 'Cardiologists',
    education: 'Government Medical College Pune',
    phoneNumber: '1234567890',
    experience: '15',
  },
  {
    name: 'Dr. Priya Sharma',
    age: '35',
    location: 'Mumbai',
    category: 'Dentists',
    education: 'Government Dental College Mumbai',
    phoneNumber: '9876543210',
    experience: '10',
  },
  {
    name: 'Dr. Aryan Patel',
    age: '45',
    location: 'Hyderabad',
    category: 'Orthopedic Surgeons',
    education: 'Government Medical College Hyderabad',
    phoneNumber: '8765432109',
    experience: '20',
  },
  {
    name: 'Dr. Nandini Gupta',
    age: '38',
    location: 'Delhi',
    category: 'Gynecologists',
    education: 'All India Institute of Medical Sciences (AIIMS) Delhi',
    phoneNumber: '7654321098',
    experience: '12',
  },
  {
    name: 'Dr. Anand Verma',
    age: '42',
    location: 'Jammu',
    category: 'Neurologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '6543210987',
    experience: '18',
  },
  {
    name: 'Dr. Priyanka Reddy',
    age: '37',
    location: 'Mumbai',
    category: 'Ophthalmologists',
    education: 'AIIMS Bangalore',
    phoneNumber: '8765432109',
    experience: '15',
  },
  {
    name: 'Dr. Mohan Singh',
    age: '44',
    location: 'Mumbai',
    category: 'Urologists',
    education: 'Government Medical College Rajasthan',
    phoneNumber: '7654321098',
    experience: '17',
  },
  {
    name: 'Dr. Sanya Kapoor',
    age: '39',
    location: 'Mumbai',
    category: 'Psychiatrists',
    education: 'Government Medical College Kashmir',
    phoneNumber: '9876543210',
    experience: '14',
  },
  {
    name: 'Dr. Sameer Joshi',
    age: '41',
    location: 'Mumbai',
    category: 'Endocrinologists',
    education: 'AIIMS Leh',
    phoneNumber: '1234567890',
    experience: '16',
  },

  {
    name: 'Dr. Akshay Gupta',
    age: '40',
    location: 'Jammu',
    category: 'Cardiologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '1234567890',
    experience: '15',
  },
  {
    name: 'Dr. Ananya Sharma',
    age: '35',
    location: 'Jammu',
    category: 'Dentists',
    education: 'Government Dental College Jammu',
    phoneNumber: '9876543210',
    experience: '10',
  },
  {
    name: 'Dr. Arjun Singh',
    age: '45',
    location: 'Jammu',
    category: 'Orthopedic Surgeons',
    education: 'Government Medical College Jammu',
    phoneNumber: '8765432109',
    experience: '20',
  },
  {
    name: 'Dr. Aisha Khan',
    age: '38',
    location: 'Jammu',
    category: 'Gynecologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '7654321098',
    experience: '12',
  },
  {
    name: 'Dr. Aditya Verma',
    age: '42',
    location: 'Jammu',
    category: 'Neurologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '6543210987',
    experience: '18',
  },
  {
    name: 'Dr. Anjali Gupta',
    age: '37',
    location: 'Jammu',
    category: 'Ophthalmologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '8765432109',
    experience: '15',
  },
  {
    name: 'Dr. Amit Kumar',
    age: '44',
    location: 'Jammu',
    category: 'Urologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '7654321098',
    experience: '17',
  },
  {
    name: 'Dr. Alia Ahmed',
    age: '39',
    location: 'Jammu',
    category: 'Psychiatrists',
    education: 'Government Medical College Jammu',
    phoneNumber: '9876543210',
    experience: '14',
  },
  {
    name: 'Dr. Ankit Joshi',
    age: '41',
    location: 'Jammu',
    category: 'Endocrinologists',
    education: 'Government Medical College Jammu',
    phoneNumber: '1234567890',
    experience: '16',
  },

  {
    name: 'Dr. Ananya Sharma',
    age: '35',
    location: 'Delhi',
    category: 'Physicians',
    education: 'All India Institute of Medical Sciences (AIIMS) Delhi',
    phoneNumber: '9876543210',
    experience: '10',
  },
  {
    name: 'Dr. Rohan Kapoor',
    age: '40',
    location: 'Delhi',
    category: 'Surgeons',
    education: 'AIIMS Delhi',
    phoneNumber: '8765432109',
    experience: '15',
  },
  {
    name: 'Dr. Priya Singh',
    age: '38',
    location: 'Delhi',
    category: 'Dentists',
    education: 'Government Dental College Delhi',
    phoneNumber: '7654321098',
    experience: '12',
  },
  {
    name: 'Dr. Arjun Verma',
    age: '45',
    location: 'Delhi',
    category: 'Pediatricians',
    education: 'AIIMS Delhi',
    phoneNumber: '6543210987',
    experience: '18',
  },
  {
    name: 'Dr. Neha Gupta',
    age: '42',
    location: 'Delhi',
    category: 'Cardiologists',
    education: 'AIIMS Delhi',
    phoneNumber: '8765432109',
    experience: '20',
  },
  {
    name: 'Dr. Rahul Sharma',
    age: '37',
    location: 'Delhi',
    category: 'Orthopedic Surgeons',
    education: 'AIIMS Delhi',
    phoneNumber: '7654321098',
    experience: '15',
  },
  {
    name: 'Dr. Simran Malhotra',
    age: '39',
    location: 'Delhi',
    category: 'Gynecologists',
    education: 'AIIMS Delhi',
    phoneNumber: '9876543210',
    experience: '14',
  },
  {
    name: 'Dr. Arnav Kumar',
    age: '41',
    location: 'Delhi',
    category: 'Ophthalmologists',
    education: 'AIIMS Delhi',
    phoneNumber: '1234567890',
    experience: '16',
  },
  {
    name: 'Dr. Natasha Gupta',
    age: '36',
    location: 'Delhi',
    category: 'Dermatologists',
    education: 'AIIMS Delhi',
    phoneNumber: '9876543210',
    experience: '11',
  },
  {
    name: 'Dr. Aditya Singh',
    age: '43',
    location: 'Delhi',
    category: 'Neurologists',
    education: 'AIIMS Delhi',
    phoneNumber: '8765432109',
    experience: '19',
  },
  {
    name: 'Dr. Aisha Ahmed',
    age: '34',
    location: 'Delhi',
    category: 'Psychiatrists',
    education: 'AIIMS Delhi',
    phoneNumber: '7654321098',
    experience: '9',
  },
  {
    name: 'Dr. Karan Kapoor',
    age: '44',
    location: 'Delhi',
    category: 'Oncologists',
    education: 'AIIMS Delhi',
    phoneNumber: '6543210987',
    experience: '21',
  },
  {
    name: 'Dr. Ritu Verma',
    age: '33',
    location: 'Delhi',
    category: 'Radiologists',
    education: 'AIIMS Delhi',
    phoneNumber: '8765432109',
    experience: '8',
  },
  {
    name: 'Dr. Vikas Yadav',
    age: '46',
    location: 'Delhi',
    category: 'Urologists',
    education: 'AIIMS Delhi',
    phoneNumber: '7654321098',
    experience: '22',
  },
  {
    name: 'Dr. Anjali Sharma',
    age: '37',
    location: 'Delhi',
    category: 'Endocrinologists',
    education: 'AIIMS Delhi',
    phoneNumber: '9876543210',
    experience: '13',
  },
  {
    name: 'Dr. Arjun Malhotra',
    age: '39',
    location: 'Delhi',
    category: 'Gastroenterologists',
    education: 'AIIMS Delhi',
    phoneNumber: '8765432109',
    experience: '15',
  },

]

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}




module.exports = dummyData;

